name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - 'docker-compose.yml'
      - 'secrets/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: self-hosted
    
    # Security: Only run on direct pushes
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy
        run: |
          cd /home/kaf/docker/n8n-stack
          git pull origin main
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
          
      - name: Status
        if: always()
        run: 'echo "Deployment: ${{ job.status }}"'

