name: Trigger Deploy

on:
  push:
    branches: [main]
    paths:
      - "docker-compose.yml"
      - "secrets/production.env.enc"
      - "scripts/deploy.sh"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.actor == 'kfuras'
    steps:
      - name: Call private workflow
        env:
          PAT: ${{ secrets.N8N_DEPLOY_PAT }}   # personal access token with repo scope
          TARGET_REF: main
        run: |
          # Extract commit message from GitHub event data, fallback to empty string if not available
          COMMIT_MSG=$(jq -r '.head_commit.message // ""' "$GITHUB_EVENT_PATH")
          
          # Create a short 7-character version of the commit SHA for identification
          SHORT_SHA=$(printf '%.7s' "$GITHUB_SHA")
          
          # Clean up commit message to create a single-line deployment label
          # 1. Convert newlines to spaces with 'tr'
          # 2. Collapse multiple whitespace characters into single spaces
          # 3. Trim leading and trailing spaces
          CLEAN_MSG=$(echo "$COMMIT_MSG" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g' | sed 's/^ //; s/ $//')
          
          # If no commit message exists, use a default format with the short SHA
          if [ -z "$CLEAN_MSG" ]; then
            CLEAN_MSG="Deploy $SHORT_SHA"
          fi
          
          # Limit deployment name to 120 characters to respect GitHub API field limits
          DEPLOY_NAME=$(printf '%s' "$CLEAN_MSG" | cut -c1-120)

          # Construct JSON payload for the workflow dispatch API call
          # Includes the target ref and the cleaned deployment name as workflow inputs
          PAYLOAD=$(jq -n \
            --arg ref "$TARGET_REF" \
            --arg name "$DEPLOY_NAME" \
            '{ref: $ref, inputs: {ref: $ref, deployment_name: $name}}')

          # Trigger the deployment workflow in the separate n8n-deploy repository
          # Uses GitHub's workflow dispatch API with personal access token authentication
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${PAT}" \
            https://api.github.com/repos/kfuras/n8n-deploy/actions/workflows/deploy.yml/dispatches \
            -d "$PAYLOAD"
