name: Trigger Deploy

on:
  push:
    branches: [main]
    paths:
      - "README.md"
      - "docker-compose.yml"
      - "secrets/production.env.enc"
      - "scripts/deploy.sh"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.actor == 'kfuras'
    steps:
      - name: Call private workflow
        env:
          PAT: ${{ secrets.N8N_DEPLOY_PAT }}   # personal access token with repo scope
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${PAT}" \
            https://api.github.com/repos/kfuras/n8n-deploy/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main","inputs":{"ref":"main"}}'
